import type {Metadata} from "next";
import {Outfit} from "next/font/google";
import "./globals.css";

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true"
        className={`${outfit.className} py-3 bg-[#222831] text-[#EEEEEE]  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
